-- ############################################################################
--  K A A L   V A S T R   —   COMPLETE DATABASE SCHEMA (fresh install)
--  Version 1.0  |  PostgreSQL 15+  |  Supabase
-- ############################################################################
--
--  PURPOSE
--    Single, authoritative schema for the Kaal Vastr storefront. Designed to
--    be pasted into a completely EMPTY Supabase project (Supabase dashboard ->
--    SQL Editor -> New query -> Run).
--
--  ORDER OF SECTIONS  (already sequential, run as one script)
--     0. Extensions & helper functions
--     1. profiles            — customer / staff / admin role directory
--     2. products            — catalogue with per colour+size stock
--     3. orders              — WhatsApp order log + dispatch status
--     4. order_status_history— immutable audit trail of dispatch changes
--     5. business_settings   — single-row store configuration
--     6. Authorization helpers (is_admin / is_staff_or_admin / is_staff_only)
--     7. Row Level Security policies
--     8. Storage bucket (product images)
--     9. Explicit grants
--    10. Seed data (store settings + 6 products)
--    11. Operator notes / first-admin bootstrap
--
--  IDEMPOTENCY
--    Every object uses IF NOT EXISTS / OR REPLACE / ON CONFLICT, so this file
--    is safe to re-run. It never drops or rewrites existing rows.
--
--  APP CONTRACT  (do not change these without changing src/lib/supabase.ts)
--    business_settings.id MUST be the text literal 'biz-001' — the client
--    updates that row with .eq('id', settings.id || 'biz-001').
--    products.id / orders.id are uuid generated by the database.
--    orders.status accepts exactly: pending | confirmed | fulfilled | cancelled
--    products.variant_stock is jsonb keyed "Color|Size" (see section 2.4).
-- ############################################################################


-- ############################################################################
-- SECTION 0 — EXTENSIONS & GENERIC HELPERS
-- ############################################################################

create extension if not exists pgcrypto with schema extensions;

-- Keeps *.updated_at fresh. Attached to every mutable table.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

comment on function public.set_updated_at() is
  'Generic BEFORE UPDATE trigger that stamps new.updated_at = now().';


-- ############################################################################
-- SECTION 1 — PROFILES  (role directory for customers, staff and admins)
-- ############################################################################
--  One row per Supabase auth user, created automatically on sign-up.
--  roles:
--    customer — may browse and place orders. Sees the cart.
--    staff    — may manage the catalogue and UPDATE ORDER DISPATCH STATUS.
--    admin    — full management, but dispatch status stays READ-ONLY.
--  Role elevation is only ever performed by the database (section 11), never
--  from client-supplied signup metadata.
-- ############################################################################

create table if not exists public.profiles (
  id            uuid primary key references auth.users (id) on delete cascade,
  email         text        not null,
  full_name     text        not null default '',
  phone         text,
  role          text        not null default 'customer'
                            check (role in ('customer', 'staff', 'admin')),
  is_active     boolean     not null default true,
  last_login_at timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),

  constraint profiles_email_present check (length(btrim(email)) > 0)
);

comment on table  public.profiles is
  'Role directory. Exactly one row per auth.users entry, created by handle_new_user().';
comment on column public.profiles.role is
  'customer | staff | admin. Staff alone may change order dispatch status.';
comment on column public.profiles.is_active is
  'Set false to disable an account without deleting its order history.';

-- Case-insensitive uniqueness: prevents the same person being added twice.
create unique index if not exists profiles_email_key
  on public.profiles (lower(email));

create index if not exists profiles_role_idx
  on public.profiles (role)
  where is_active;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
  before update on public.profiles
  for each row execute function public.set_updated_at();

-- Auto-create the profile on sign-up. Role is ALWAYS 'customer' here: a
-- client cannot self-assign staff/admin by crafting signup metadata.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    'customer'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- ############################################################################
-- SECTION 2 — PRODUCTS  (catalogue with per colour+size stock)
-- ############################################################################

create table if not exists public.products (
  id               uuid primary key default gen_random_uuid(),
  name             text          not null,
  category         text          not null,
  brand            text          not null default 'Kaal Vastr',
  sku              text          not null,
  description      text,
  selling_price    numeric(10,2) not null check (selling_price >= 0),
  compare_at_price numeric(10,2) check (compare_at_price is null or compare_at_price >= 0),
  sizes            text[]        not null default array['S','M','L','XL']::text[],
  colors           text[]        not null default array['Charcoal','Black','Silver']::text[],
  -- 2.4 Per-variant stock. See the dedicated comment below.
  variant_stock    jsonb,
  -- 2.5 Total units. Auto-derived from variant_stock when that is set.
  stock            integer       not null default 0 check (stock >= 0),
  image_url        text,
  images           text[]        not null default array[]::text[],
  is_available     boolean       not null default true,
  is_archived      boolean       not null default false,
  created_at       timestamptz   not null default now(),
  updated_at       timestamptz   not null default now(),

  constraint products_sku_present   check (length(btrim(sku)) > 0),
  constraint products_name_present  check (length(btrim(name)) > 0),
  constraint products_sizes_present check (cardinality(sizes) > 0),
  constraint products_colors_present check (cardinality(colors) > 0)
);

comment on table  public.products is
  'Product catalogue. Readable by everyone; writable by admins only (section 7).';
comment on column public.products.sku is
  'Human-readable stock keeping unit, unique across the catalogue.';
comment on column public.products.sizes is
  'Size labels offered, e.g. {S,M,L,XL}. Drives the variant stock grid.';
comment on column public.products.colors is
  'Colour names offered, e.g. {Obsidian Black,Charcoal Grey}.';
comment on column public.products.stock is
  'Total sellable units. When variant_stock is set this column is overwritten '
  'by the sum of the variants and must not be written directly by the client.';
comment on column public.products.is_available is
  'false hides the product from the storefront. Forced to false when total '
  'variant stock reaches zero.';

-- 2.1 Unique SKU
create unique index if not exists products_sku_key on public.products (sku);

-- 2.2 Catalogue browsing: active products, plus category/price for filtering.
create index if not exists products_browse_idx
  on public.products (category, selling_price)
  where is_archived = false;

create index if not exists products_archived_idx
  on public.products (is_archived);

-- 2.3 updated_at maintenance
drop trigger if exists trg_products_updated_at on public.products;
create trigger trg_products_updated_at
  before update on public.products
  for each row execute function public.set_updated_at();

-- 2.4 variant_stock format
comment on column public.products.variant_stock is
  'Per colour+size stock, keyed "Color|Size" with a non-negative integer value, '
  'e.g. {"Obsidian Black|S":4,"Obsidian Black|M":0,"Charcoal Grey|XL":3}. '
  'NULL or {} means the product uses the flat stock column only. '
  'A colour+size absent from the map is treated as 0 (out of stock). '
  'Maintained by the admin product form; validated by '
  'products_variant_stock_is_valid() and totalled by products_sync_total_stock().';

-- 2.4a Reject malformed variant payloads before they reach the table.
--      Trigger function: volatility is intentionally left at the default
--      because it raises exceptions rather than computing a value.
create or replace function public.products_variant_stock_is_valid()
returns trigger
language plpgsql
as $$
declare
  entry jsonb;
begin
  if new.variant_stock is null or new.variant_stock = '{}'::jsonb then
    return new;
  end if;

  if jsonb_typeof(new.variant_stock) <> 'object' then
    raise exception 'variant_stock must be a JSON object keyed "Color|Size"';
  end if;

  for entry in select * from jsonb_each(new.variant_stock) loop
    if entry.key !~ '\|' then
      raise exception 'variant_stock key "%" must be in the form "Color|Size"', entry.key;
    end if;

    if jsonb_typeof(entry.value) <> 'number'
       or (entry.value #>> '{}')::numeric < 0
       or (entry.value #>> '{}')::numeric <> trunc((entry.value #>> '{}')::numeric) then
      raise exception 'variant_stock["%"] must be a non-negative whole number', entry.key;
    end if;
  end loop;

  return new;
end;
$$;

drop trigger if exists trg_products_variant_stock_valid on public.products;
create trigger trg_products_variant_stock_valid
  before insert or update of variant_stock on public.products
  for each row execute function public.products_variant_stock_is_valid();

-- 2.5 Keep the flat stock total and availability in step with the variants, so
--     list views and sales analytics stay correct without extra joins.
create or replace function public.products_sync_total_stock()
returns trigger
language plpgsql
as $$
declare
  total integer;
begin
  if new.variant_stock is not null
     and jsonb_typeof(new.variant_stock) = 'object'
     and new.variant_stock <> '{}'::jsonb then

    select coalesce(sum(value::text::numeric), 0)::integer
      into total
      from jsonb_each_text(new.variant_stock);

    new.stock := total;

    if total = 0 then
      new.is_available := false;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_products_sync_total_stock on public.products;
create trigger trg_products_sync_total_stock
  before insert or update of variant_stock on public.products
  for each row execute function public.products_sync_total_stock();


-- ############################################################################
-- SECTION 3 — ORDERS  (WhatsApp order log + dispatch status)
-- ############################################################################
--  Written by the storefront at checkout, read by staff and admins, and only
--  the `status` column is updatable — and only by a staff account.
-- ############################################################################

create table if not exists public.orders (
  id              uuid primary key default gen_random_uuid(),
  customer_name   text          not null,
  customer_phone  text          not null,
  address_notes   text,
  -- Array of {product_id, product_name, size, color, quantity, price}.
  items           jsonb         not null default '[]'::jsonb,
  subtotal        numeric(10,2) not null default 0 check (subtotal >= 0),
  total_amount    numeric(10,2) not null default 0 check (total_amount >= 0),
  status          text          not null default 'pending'
                                check (status in ('pending','confirmed','fulfilled','cancelled')),
  -- Dispatch audit. Written by the database, read by the dashboard.
  dispatch_note   text,
  status_updated_by uuid        references public.profiles (id) on delete set null,
  status_updated_at timestamptz,
  created_at      timestamptz   not null default now(),
  updated_at      timestamptz   not null default now(),

  constraint orders_customer_name_present  check (length(btrim(customer_name)) > 0),
  constraint orders_customer_phone_present check (length(btrim(customer_phone)) > 0),
  constraint orders_items_is_array         check (jsonb_typeof(items) = 'array')
);

comment on table  public.orders is
  'Customer orders placed through the WhatsApp checkout flow.';
comment on column public.orders.status is
  'pending -> confirmed -> fulfilled, or cancelled. Only staff may change it.';
comment on column public.orders.items is
  'JSON array of order lines: {product_id, product_name, size, color, quantity, price}.';
comment on column public.orders.status_updated_by is
  'Staff account that last moved the dispatch status. Null until first change.';
comment on column public.orders.status_updated_at is
  'Timestamp of the last dispatch status change.';

create index if not exists orders_status_idx  on public.orders (status);
create index if not exists orders_created_idx on public.orders (created_at desc);
create index if not exists orders_phone_idx   on public.orders (customer_phone);

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at
  before update on public.orders
  for each row execute function public.set_updated_at();


-- ############################################################################
-- SECTION 4 — ORDER STATUS HISTORY  (immutable dispatch audit trail)
-- ############################################################################
--  Append-only. A trigger writes one row per dispatch change, so it stays
--  correct no matter which client performs the update.
-- ############################################################################

create table if not exists public.order_status_history (
  id          bigint generated always as identity primary key,
  order_id    uuid        not null references public.orders (id) on delete cascade,
  from_status text,
  to_status   text        not null,
  changed_by  uuid        references public.profiles (id) on delete set null,
  note        text,
  created_at  timestamptz not null default now()
);

comment on table public.order_status_history is
  'Append-only audit trail of order dispatch status changes.';

create index if not exists order_status_history_order_idx
  on public.order_status_history (order_id, created_at desc);


-- ############################################################################
-- SECTION 5 — BUSINESS SETTINGS  (single-row store configuration)
-- ############################################################################
--  The CHECK constraint enforces a single row, so the client can safely
--  address it as id = 'biz-001'.
-- ############################################################################

create table if not exists public.business_settings (
  id             text primary key default 'biz-001',
  business_name  text        not null default 'Kaal Vastr',
  description    text,
  whatsapp_number text       not null default '',
  mobile_number  text,
  email          text,
  address        text,
  store_timings  text,
  instagram_url  text,
  facebook_url   text,
  logo_url       text,
  updated_at     timestamptz not null default now(),

  -- Guarantees exactly one configuration row.
  constraint business_settings_singleton check (id = 'biz-001')
);

comment on table  public.business_settings is
  'Store-wide configuration. Exactly one row, id = ''biz-001''.';
comment on column public.business_settings.whatsapp_number is
  'WhatsApp number in international format, digits only, e.g. 919876543210.';

drop trigger if exists trg_business_settings_updated_at on public.business_settings;
create trigger trg_business_settings_updated_at
  before update on public.business_settings
  for each row execute function public.set_updated_at();


-- ############################################################################
-- SECTION 6 — AUTHORIZATION HELPERS
-- ############################################################################
--  SECURITY DEFINER so that RLS on profiles can never make these recurse.
--  They read the caller's JWT (auth.uid()), never a value from the client.
-- ############################################################################

-- Is the caller an admin?
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and is_active
  );
$$;

-- May the caller operate the dashboard at all?
create or replace function public.is_staff_or_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role in ('admin','staff') and is_active
  );
$$;

-- May the caller change order dispatch status? Staff only — never admin.
create or replace function public.is_staff_only()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'staff' and is_active
  );
$$;


-- ############################################################################
-- SECTION 7 — ROW LEVEL SECURITY
-- ############################################################################
--  Summary of the access model:
--    products            read: everyone | write: admin
--    orders              insert: anyone (checkout) | read: staff+admin
--                        update(status): staff ONLY | delete: admin
--    order_status_history read: staff+admin | insert: via trigger only
--    business_settings   read: everyone | write: admin
--    profiles            read: staff+admin (staff/admin rows) + own row
--                        update: self (non-privileged fields) or admin
-- ############################################################################

-- 7.1 PRODUCTS -------------------------------------------------------------
alter table public.products enable row level security;

drop policy if exists "products_public_read" on public.products;
create policy "products_public_read"
  on public.products for select
  using (is_archived = false);

drop policy if exists "products_admin_read_all" on public.products;
create policy "products_admin_read_all"
  on public.products for select
  using (public.is_admin());

drop policy if exists "products_admin_insert" on public.products;
create policy "products_admin_insert"
  on public.products for insert
  with check (public.is_admin());

drop policy if exists "products_admin_update" on public.products;
create policy "products_admin_update"
  on public.products for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "products_admin_delete" on public.products;
create policy "products_admin_delete"
  on public.products for delete
  using (public.is_admin());

-- 7.2 ORDERS ---------------------------------------------------------------
alter table public.orders enable row level security;

-- Customers may log their own order during checkout and nothing more.
drop policy if exists "orders_public_insert" on public.orders;
create policy "orders_public_insert"
  on public.orders for insert
  with check (true);

drop policy if exists "orders_staff_read" on public.orders;
create policy "orders_staff_read"
  on public.orders for select
  using (public.is_staff_or_admin());

-- Dispatch status is staff-only. Admins keep read-only visibility.
drop policy if exists "orders_staff_update_status" on public.orders;
create policy "orders_staff_update_status"
  on public.orders for update
  using (public.is_staff_only())
  with check (public.is_staff_only());

drop policy if exists "orders_admin_delete" on public.orders;
create policy "orders_admin_delete"
  on public.orders for delete
  using (public.is_admin());

-- Row-level safety net: even if a wider UPDATE grant is ever restored, an
-- admin can never move a dispatch status.
create or replace function public.orders_block_admin_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status is distinct from old.status and not public.is_staff_only() then
    raise exception 'Only staff accounts can update the dispatch status';
  end if;

  if new.status is distinct from old.status then
    new.status_updated_by := auth.uid();
    new.status_updated_at := now();
  end if;

  return new;
end;
$$;

drop trigger if exists trg_orders_staff_only_status on public.orders;
create trigger trg_orders_staff_only_status
  before update on public.orders
  for each row execute function public.orders_block_admin_status_change();

-- Append the audit row whenever the status actually changes.
create or replace function public.log_order_status_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status is distinct from old.status then
    insert into public.order_status_history
      (order_id, from_status, to_status, changed_by, note)
    values
      (new.id, old.status, new.status, auth.uid(), new.dispatch_note);
  end if;
  return new;
end;
$$;

drop trigger if exists trg_orders_log_status on public.orders;
create trigger trg_orders_log_status
  after update on public.orders
  for each row execute function public.log_order_status_change();

-- 7.3 ORDER STATUS HISTORY -------------------------------------------------
alter table public.order_status_history enable row level security;

drop policy if exists "order_status_history_staff_read" on public.order_status_history;
create policy "order_status_history_staff_read"
  on public.order_status_history for select
  using (public.is_staff_or_admin());

-- No INSERT policy: rows are written only by the SECURITY DEFINER trigger,
-- so a client cannot forge audit entries.

-- 7.4 BUSINESS SETTINGS ----------------------------------------------------
alter table public.business_settings enable row level security;

drop policy if exists "business_settings_public_read" on public.business_settings;
create policy "business_settings_public_read"
  on public.business_settings for select
  using (true);

drop policy if exists "business_settings_admin_insert" on public.business_settings;
create policy "business_settings_admin_insert"
  on public.business_settings for insert
  with check (public.is_admin());

drop policy if exists "business_settings_admin_update" on public.business_settings;
create policy "business_settings_admin_update"
  on public.business_settings for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "business_settings_admin_delete" on public.business_settings;
create policy "business_settings_admin_delete"
  on public.business_settings for delete
  using (public.is_admin());

-- 7.5 PROFILES ------------------------------------------------------------
alter table public.profiles enable row level security;

-- A user may always read their own row.
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own"
  on public.profiles for select
  using (auth.uid() = id);

-- Staff and admins may read the staff/admin directory (never customers').
drop policy if exists "profiles_staff_directory_read" on public.profiles;
create policy "profiles_staff_directory_read"
  on public.profiles for select
  using (public.is_staff_or_admin() and role in ('admin','staff'));

-- Self-service update, but a user may not change their own role.
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
  on public.profiles for update
  using (auth.uid() = id)
  with check (
    auth.uid() = id
    and role = (select p.role from public.profiles p where p.id = auth.uid())
  );

-- Admins may edit any profile (role changes included).
drop policy if exists "profiles_admin_update" on public.profiles;
create policy "profiles_admin_update"
  on public.profiles for update
  using (public.is_admin())
  with check (true);

-- ############################################################################
-- SECTION 8 — STORAGE (product image bucket)
-- ############################################################################

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

drop policy if exists "product_images_public_read" on storage.objects;
create policy "product_images_public_read"
  on storage.objects for select
  using (bucket_id = 'product-images');

drop policy if exists "product_images_admin_insert" on storage.objects;
create policy "product_images_admin_insert"
  on storage.objects for insert
  with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "product_images_admin_update" on storage.objects;
create policy "product_images_admin_update"
  on storage.objects for update
  using (bucket_id = 'product-images' and public.is_admin())
  with check (bucket_id = 'product-images' and public.is_admin());

drop policy if exists "product_images_admin_delete" on storage.objects;
create policy "product_images_admin_delete"
  on storage.objects for delete
  using (bucket_id = 'product-images' and public.is_admin());


-- ############################################################################
-- SECTION 9 — EXPLICIT GRANTS
-- ############################################################################
--  Deterministic across hosted and local projects. Note the column-scoped
--  UPDATE on orders: staff can change `status` and nothing else.
-- ############################################################################

grant usage on schema public to anon, authenticated;

-- products: world-readable, staff-writable (RLS narrows writes to admins)
grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;

-- orders: checkout insert for everyone; staff read; staff-only status update
grant insert, select on public.orders to anon, authenticated;
revoke update on public.orders from anon, authenticated;
grant update (status) on public.orders to authenticated;
grant delete on public.orders to authenticated;

-- dispatch audit trail: readable by staff, written only by trigger
grant select on public.order_status_history to authenticated;

-- store settings: world-readable, admin-writable
grant select on public.business_settings to anon, authenticated;
grant insert, update, delete on public.business_settings to authenticated;

-- profiles
grant select on public.profiles to anon, authenticated;
grant update on public.profiles to authenticated;


-- ############################################################################
-- SECTION 10 — ROLE MANAGEMENT (admin-only, server-side)
-- ############################################################################
--  Run these from the Supabase SQL editor, never from the browser.
--  Both keep auth.users.raw_user_meta_data in sync as a client-side cache.
-- ############################################################################

-- 10.1 Promote an existing account to admin (first-admin bootstrap).
create or replace function public.promote_to_admin(target_email text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.profiles p
     set role = 'admin'
    from auth.users u
   where u.id = p.id
     and lower(u.email) = lower(target_email);

  if not found then
    raise exception 'No account found for %. Sign the user up first.', target_email;
  end if;

  update auth.users u
     set raw_user_meta_data = coalesce(u.raw_user_meta_data, '{}'::jsonb)
                             || jsonb_build_object('role', 'admin')
   where lower(u.email) = lower(target_email);
end;
$$;

-- 10.2 Set any account's role. Callable by signed-in admins only.
create or replace function public.set_user_role(target_email text, new_role text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Only admins can change account roles';
  end if;

  if new_role not in ('customer', 'staff', 'admin') then
    raise exception 'Invalid role: % (expected customer, staff or admin)', new_role;
  end if;

  update public.profiles p
     set role = new_role
    from auth.users u
   where u.id = p.id
     and lower(u.email) = lower(target_email);

  if not found then
    raise exception 'No account found for %', target_email;
  end if;

  update auth.users u
     set raw_user_meta_data = coalesce(u.raw_user_meta_data, '{}'::jsonb)
                             || jsonb_build_object('role', new_role)
   where lower(u.email) = lower(target_email);
end;
$$;

-- 10.3 Enable / disable an account without deleting its history.
create or replace function public.set_user_active(target_email text, active boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Only admins can change account status';
  end if;

  update public.profiles p
     set is_active = active
    from auth.users u
   where u.id = p.id
     and lower(u.email) = lower(target_email);

  if not found then
    raise exception 'No account found for %', target_email;
  end if;
end;
$$;

revoke all on function public.set_user_role(text, text)   from public, anon;
revoke all on function public.set_user_active(text, boolean) from public, anon;
grant execute on function public.set_user_role(text, text)      to authenticated;
grant execute on function public.set_user_active(text, boolean) to authenticated;

-- Repair any account whose metadata cache drifted from profiles.role.
update auth.users u
   set raw_user_meta_data = coalesce(u.raw_user_meta_data, '{}'::jsonb)
                           || jsonb_build_object('role', p.role)
  from public.profiles p
 where p.id = u.id
   and (u.raw_user_meta_data ->> 'role') is distinct from p.role;


-- ############################################################################
-- SECTION 11 — SEED DATA
-- ############################################################################
--  Mirrors the storefront fallback data in src/lib/supabase.ts so a fresh
--  database looks identical to a fresh browser.
-- ############################################################################

insert into public.business_settings
  (id, business_name, description, whatsapp_number, mobile_number, email,
   address, store_timings, instagram_url, facebook_url, logo_url)
values
  ('biz-001',
   'Kaal Vastr',
   'Minimalist dark grey & silver aesthetic streetwear and luxury clothing.',
   '919876543210',
   '+91 98765 43210',
   'contact@kaalvastr.in',
   '104, Obsidian Avenue, Khar West, Mumbai, MH 400052',
   'Mon - Sat: 11:00 AM - 9:00 PM | Sun: 12:00 PM - 7:00 PM',
   'https://instagram.com/kaalvastr',
   'https://facebook.com/kaalvastr',
   '')
on conflict (id) do update set
  business_name  = excluded.business_name,
  description    = excluded.description,
  whatsapp_number = excluded.whatsapp_number,
  mobile_number  = excluded.mobile_number,
  email          = excluded.email,
  address        = excluded.address,
  store_timings  = excluded.store_timings,
  instagram_url  = excluded.instagram_url,
  facebook_url   = excluded.facebook_url,
  logo_url       = excluded.logo_url;

insert into public.products
  (name, category, brand, sku, description, selling_price, compare_at_price,
   sizes, colors, variant_stock, stock, image_url, images, is_available, is_archived)
values
  ('Shadow Oversized Hoodie', 'Hoodies', 'Kaal Vastr', 'KV-HD-001',
   'Heavyweight 450 GSM French Terry cotton hoodie in deep obsidian black. Features dropped shoulders, double-stitched seams, and minimal silver branding.',
   4499, 5999,
   array['S','M','L','XL']::text[], array['Obsidian Black','Charcoal Grey']::text[],
   '{"Obsidian Black|S":4,"Obsidian Black|M":6,"Obsidian Black|L":5,"Obsidian Black|XL":3,"Charcoal Grey|S":3,"Charcoal Grey|M":0,"Charcoal Grey|L":2,"Charcoal Grey|XL":2}'::jsonb,
   25,
   'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
   array[
     'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
     'https://images.unsplash.com/photo-1509967419530-da38b4704bc6?auto=format&fit=crop&w=800&q=80'
   ]::text[],
   true, false),

  ('Obsidian Acid-Wash Tee', 'T-Shirts', 'Kaal Vastr', 'KV-TS-002',
   'Custom vintage acid-washed 260 GSM combed cotton t-shirt featuring subtle silver typography on the chest.',
   2199, 2799,
   array['S','M','L','XL','XXL']::text[], array['Acid Black','Silver Dust']::text[],
   null, 25,
   'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
   array['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80']::text[],
   true, false),

  ('Monolith Utility Cargo Pants', 'Pants', 'Kaal Vastr', 'KV-PT-003',
   'Tapered cargo trousers constructed from weather-resistant ripstop canvas with 6 tactical pockets and adjustable ankles.',
   4999, 6499,
   array['M','L','XL']::text[], array['Charcoal Grey','Deep Black']::text[],
   null, 8,
   'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=800&q=80',
   array['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=800&q=80']::text[],
   true, false),

  ('Nocturne Bomber Jacket', 'Outerwear', 'Kaal Vastr', 'KV-JK-004',
   'Minimalist matte black nylon bomber jacket with brushed silver zippers and premium satin thermal lining.',
   7999, 9999,
   array['S','M','L']::text[], array['Matte Black']::text[],
   null, 5,
   'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=800&q=80',
   array['https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=800&q=80']::text[],
   true, false),

  ('Vanguard Sweatshirt', 'Sweatshirts', 'Kaal Vastr', 'KV-SW-005',
   'Structured French terry crewneck with tonal embroidered Kaal Vastr chest crest and rib-knit cuffs.',
   3499, 4299,
   array['S','M','L','XL']::text[], array['Steel Grey','Coal Black']::text[],
   null, 12,
   'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?auto=format&fit=crop&w=800&q=80',
   array['https://images.unsplash.com/photo-1578587018452-892bacefd3f2?auto=format&fit=crop&w=800&q=80']::text[],
   true, false),

  ('Eclipse Structured Blazer', 'Outerwear', 'Kaal Vastr', 'KV-BL-006',
   'Modern unconstructed tailored jacket crafted from premium wool-blend twill with clean lapels and minimal silver hardware.',
   8999, 11999,
   array['M','L','XL']::text[], array['Charcoal Grey']::text[],
   null, 4,
   'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
   array['https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80']::text[],
   true, false)
on conflict (sku) do nothing;


-- ############################################################################
-- SECTION 12 — FIRST-ADMIN BOOTSTRAP  (run separately, after this script)
-- ############################################################################
--
--  Step 1. Sign up through the app at /admin/register (this creates the
--          auth user and a profiles row with role 'customer').
--  Step 2. Run the statement below in the SQL editor, substituting your email.
--
--    select public.promote_to_admin('you@example.com');
--
--  Verify:
--    select email, role, is_active from public.profiles order by created_at;
--
--  Thereafter, promote staff from Dashboard -> Team -> Send Invite, or with:
--    select public.set_user_role('staff@example.com', 'staff');
--
--  Staff may change order dispatch status. Admins may not.
-- ############################################################################
